# Generated by Django 2.2.4 on 2019-08-19 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keto', '0002_meal_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
